# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grzegorz/Projects/KursC/szkolenie/11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grzegorz/Projects/KursC/szkolenie/11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grzegorz/Projects/KursC/szkolenie/11/CMakeFiles /home/grzegorz/Projects/KursC/szkolenie/11/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grzegorz/Projects/KursC/szkolenie/11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 11_01

# Build rule for target.
11_01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 11_01
.PHONY : 11_01

# fast build rule for target.
11_01/fast:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/build
.PHONY : 11_01/fast

11_01.o: 11_01.c.o

.PHONY : 11_01.o

# target to build an object file
11_01.c.o:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/11_01.c.o
.PHONY : 11_01.c.o

11_01.i: 11_01.c.i

.PHONY : 11_01.i

# target to preprocess a source file
11_01.c.i:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/11_01.c.i
.PHONY : 11_01.c.i

11_01.s: 11_01.c.s

.PHONY : 11_01.s

# target to generate assembly for a file
11_01.c.s:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/11_01.c.s
.PHONY : 11_01.c.s

stud_console.o: stud_console.c.o

.PHONY : stud_console.o

# target to build an object file
stud_console.c.o:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_console.c.o
.PHONY : stud_console.c.o

stud_console.i: stud_console.c.i

.PHONY : stud_console.i

# target to preprocess a source file
stud_console.c.i:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_console.c.i
.PHONY : stud_console.c.i

stud_console.s: stud_console.c.s

.PHONY : stud_console.s

# target to generate assembly for a file
stud_console.c.s:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_console.c.s
.PHONY : stud_console.c.s

stud_file.o: stud_file.c.o

.PHONY : stud_file.o

# target to build an object file
stud_file.c.o:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_file.c.o
.PHONY : stud_file.c.o

stud_file.i: stud_file.c.i

.PHONY : stud_file.i

# target to preprocess a source file
stud_file.c.i:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_file.c.i
.PHONY : stud_file.c.i

stud_file.s: stud_file.c.s

.PHONY : stud_file.s

# target to generate assembly for a file
stud_file.c.s:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_file.c.s
.PHONY : stud_file.c.s

stud_sort.o: stud_sort.c.o

.PHONY : stud_sort.o

# target to build an object file
stud_sort.c.o:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_sort.c.o
.PHONY : stud_sort.c.o

stud_sort.i: stud_sort.c.i

.PHONY : stud_sort.i

# target to preprocess a source file
stud_sort.c.i:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_sort.c.i
.PHONY : stud_sort.c.i

stud_sort.s: stud_sort.c.s

.PHONY : stud_sort.s

# target to generate assembly for a file
stud_sort.c.s:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_sort.c.s
.PHONY : stud_sort.c.s

stud_utils.o: stud_utils.c.o

.PHONY : stud_utils.o

# target to build an object file
stud_utils.c.o:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_utils.c.o
.PHONY : stud_utils.c.o

stud_utils.i: stud_utils.c.i

.PHONY : stud_utils.i

# target to preprocess a source file
stud_utils.c.i:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_utils.c.i
.PHONY : stud_utils.c.i

stud_utils.s: stud_utils.c.s

.PHONY : stud_utils.s

# target to generate assembly for a file
stud_utils.c.s:
	$(MAKE) -f CMakeFiles/11_01.dir/build.make CMakeFiles/11_01.dir/stud_utils.c.s
.PHONY : stud_utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... 11_01"
	@echo "... edit_cache"
	@echo "... 11_01.o"
	@echo "... 11_01.i"
	@echo "... 11_01.s"
	@echo "... stud_console.o"
	@echo "... stud_console.i"
	@echo "... stud_console.s"
	@echo "... stud_file.o"
	@echo "... stud_file.i"
	@echo "... stud_file.s"
	@echo "... stud_sort.o"
	@echo "... stud_sort.i"
	@echo "... stud_sort.s"
	@echo "... stud_utils.o"
	@echo "... stud_utils.i"
	@echo "... stud_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

